/**
 * SWAPXRESTB2BAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const APIException = require('./APIException');

/**
 * Creates an instance of SwapXCoreServicesV2ModelsUserWalletWalletAmountErrorException
 */
class SwapXCoreServicesV2ModelsUserWalletWalletAmountErrorException extends APIException {
    /**
     * @constructor
     */
    constructor() {
        super();
        /**
         * TODO: Write general description for this field
         */
        this.currencyId = null;

        /**
         * TODO: Write general description for this field
         */
        this.amount = null;
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'currencyId', realName: 'currencyId' },
            { name: 'amount', realName: 'amount' },
        ]);
    }
}

module.exports = SwapXCoreServicesV2ModelsUserWalletWalletAmountErrorException;
