/**
 * SWAPXRESTB2BAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const CardStatusEnum = {

    /**
     * TODO: Write general description for this element
     */
    NO_CARD: 'NoCard',

    /**
     * TODO: Write general description for this element
     */
    INACTIVE: 'Inactive',

    /**
     * TODO: Write general description for this element
     */
    ACTIVE: 'Active',

    /**
     * TODO: Write general description for this element
     */
    LOST_STOLEN: 'LostStolen',

    /**
     * TODO: Write general description for this element
     */
    LOST: 'Lost',

    /**
     * TODO: Write general description for this element
     */
    STOLEN: 'Stolen',

    /**
     * TODO: Write general description for this element
     */
    DAMAGED: 'Damaged',

    /**
     * TODO: Write general description for this element
     */
    EXPIRED: 'Expired',

    /**
     * TODO: Write general description for this element
     */
    BLOCKED: 'Blocked',

    /**
     * TODO: Write general description for this element
     */
    NOT_FOUND: 'NotFound',

    /**
     * TODO: Write general description for this element
     */
    BLOCKED_BY_SWAPX_ADMIN: 'BlockedBySwapxAdmin',

    /**
     * TODO: Write general description for this element
     */
    BLOCKED_BY_ORG_ADMIN: 'BlockedByOrgAdmin',

};

module.exports = CardStatusEnum;
