/**
 * SWAPXRESTB2BAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const FrequencyEnum = {

    /**
     * TODO: Write general description for this element
     */
    SINGLE_TRIP: 'SingleTrip',

    /**
     * TODO: Write general description for this element
     */
    ANNUAL: 'Annual',

    /**
     * TODO: Write general description for this element
     */
    LONG_STAY: 'LongStay',

};

module.exports = FrequencyEnum;
