/**
 * SWAPXRESTB2BAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const GroupTypeEnum = {

    /**
     * TODO: Write general description for this element
     */
    INDIVIDUAL: 'Individual',

    /**
     * TODO: Write general description for this element
     */
    COUPLE: 'Couple',

    /**
     * TODO: Write general description for this element
     */
    SINGLE_PARENT_FAMILY: 'SingleParentFamily',

    /**
     * TODO: Write general description for this element
     */
    FAMILY: 'Family',

};

module.exports = GroupTypeEnum;
