/**
 * SWAPXRESTB2BAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const InsuranceTypeEnum = {

    /**
     * TODO: Write general description for this element
     */
    TRAVEL_INSURANCE: 'TravelInsurance',

    /**
     * TODO: Write general description for this element
     */
    GADGET_INSURANCE: 'GadgetInsurance',

    /**
     * TODO: Write general description for this element
     */
    MEDICAL_INSURANCE: 'MedicalInsurance',

    /**
     * TODO: Write general description for this element
     */
    COLLISION_INSURANCE: 'CollisionInsurance',

    /**
     * TODO: Write general description for this element
     */
    TRAVEL_AND_GADGET: 'TravelAndGadget',

    /**
     * TODO: Write general description for this element
     */
    TRAVEL_AND_MEDICAL: 'TravelAndMedical',

    /**
     * TODO: Write general description for this element
     */
    TRAVEL_AND_MEDICAL_AND_GADGET: 'TravelAndMedicalAndGadget',

    /**
     * TODO: Write general description for this element
     */
    CAR_HIRE_EXPRESS: 'CarHireExpress',

};

module.exports = InsuranceTypeEnum;
