/**
 * SWAPXRESTB2BAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const OrderByEnum = {

    /**
     * TODO: Write general description for this element
     */
    ASC: 'ASC',

    /**
     * TODO: Write general description for this element
     */
    DESC: 'DESC',

};

module.exports = OrderByEnum;
