/**
 * SWAPXRESTB2BAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const SortBy1Enum = {

    /**
     * TODO: Write general description for this element
     */
    DATE: 'Date',

    /**
     * TODO: Write general description for this element
     */
    ACTIVITY: 'Activity',

    /**
     * TODO: Write general description for this element
     */
    DETAILS: 'Details',

    /**
     * TODO: Write general description for this element
     */
    AMOUNT: 'Amount',

};

module.exports = SortBy1Enum;
