/**
 * SWAPXRESTB2BAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const SortByEnum = {

    /**
     * TODO: Write general description for this element
     */
    NAME: 'Name',

    /**
     * TODO: Write general description for this element
     */
    DATE: 'Date',

    /**
     * TODO: Write general description for this element
     */
    POLICY: 'Policy',

    /**
     * TODO: Write general description for this element
     */
    CLAIM_ID: 'ClaimId',

    /**
     * TODO: Write general description for this element
     */
    CLAIM_STATUS: 'ClaimStatus',

};

module.exports = SortByEnum;
