/**
 * SWAPXRESTB2BAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const StatusEnum = {

    /**
     * TODO: Write general description for this element
     */
    ROCK_ACTIVE: 'RockActive',

    /**
     * TODO: Write general description for this element
     */
    ACTIVE: 'Active',

    /**
     * TODO: Write general description for this element
     */
    CANCELLED: 'Cancelled',

    /**
     * TODO: Write general description for this element
     */
    DELETED: 'Deleted',

};

module.exports = StatusEnum;
