/**
 * SWAPXRESTB2BAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of SwapXRESTB2BModelsUsersUpdateUser3DSInfoModel
 */
class SwapXRESTB2BModelsUsersUpdateUser3DSInfoModel extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.userId = this.constructor.getValue(obj.userId);
        this.memorableName = this.constructor.getValue(obj.memorableName);
        this.memorablePlace = this.constructor.getValue(obj.memorablePlace);
        this.memorableDate = this.constructor.getValue(obj.memorableDate);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'userId', realName: 'userId' },
            { name: 'memorableName', realName: 'memorableName' },
            { name: 'memorablePlace', realName: 'memorablePlace' },
            {
                name: 'memorableDate',
                realName: 'memorableDate',
                isDateTime: true,
                dateTimeValue: 'rfc3339',
            },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = SwapXRESTB2BModelsUsersUpdateUser3DSInfoModel;
