/**
 * SWAPXRESTB2BAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of SwapXRESTB2BModelsUsersUpdateUserAccountBlockModel
 */
class SwapXRESTB2BModelsUsersUpdateUserAccountBlockModel extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.userId = this.constructor.getValue(obj.userId);
        this.isBlockAccount = this.constructor.getValue(obj.isBlockAccount);
        this.reason = this.constructor.getValue(obj.reason);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'userId', realName: 'userId' },
            { name: 'isBlockAccount', realName: 'isBlockAccount' },
            { name: 'reason', realName: 'reason' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = SwapXRESTB2BModelsUsersUpdateUserAccountBlockModel;
