/**
 * SWAPXRESTB2BAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of SwapXRESTB2BModelsUsersUpdateUserModel
 */
class SwapXRESTB2BModelsUsersUpdateUserModel extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.id = this.constructor.getValue(obj.id);
        this.firstName = this.constructor.getValue(obj.firstName);
        this.lastName = this.constructor.getValue(obj.lastName);
        this.email = this.constructor.getValue(obj.email);
        this.emailConfirmed = this.constructor.getValue(obj.emailConfirmed);
        this.password = this.constructor.getValue(obj.password);
        this.mobileNumber = this.constructor.getValue(obj.mobileNumber);
        this.mobileNumberConfirmed = this.constructor.getValue(obj.mobileNumberConfirmed);
        this.dateOfBirth = this.constructor.getValue(obj.dateOfBirth);
        this.countryId = this.constructor.getValue(obj.countryId);
        this.houseNameNumber = this.constructor.getValue(obj.houseNameNumber);
        this.street = this.constructor.getValue(obj.street);
        this.address2 = this.constructor.getValue(obj.address2);
        this.city = this.constructor.getValue(obj.city);
        this.postCode = this.constructor.getValue(obj.postCode);
        this.groupId = this.constructor.getValue(obj.groupId);
        this.kycStatus = this.constructor.getValue(obj.kycStatus);
        this.accountBlocked = this.constructor.getValue(obj.accountBlocked);
        this.isDeleted = this.constructor.getValue(obj.isDeleted);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'id', realName: 'id' },
            { name: 'firstName', realName: 'firstName' },
            { name: 'lastName', realName: 'lastName' },
            { name: 'email', realName: 'email' },
            { name: 'emailConfirmed', realName: 'emailConfirmed' },
            { name: 'password', realName: 'password' },
            { name: 'mobileNumber', realName: 'mobileNumber' },
            { name: 'mobileNumberConfirmed', realName: 'mobileNumberConfirmed' },
            {
                name: 'dateOfBirth',
                realName: 'dateOfBirth',
                isDateTime: true,
                dateTimeValue: 'rfc3339',
            },
            { name: 'countryId', realName: 'countryId' },
            { name: 'houseNameNumber', realName: 'houseNameNumber' },
            { name: 'street', realName: 'street' },
            { name: 'address2', realName: 'address2' },
            { name: 'city', realName: 'city' },
            { name: 'postCode', realName: 'postCode' },
            { name: 'groupId', realName: 'groupId' },
            { name: 'kycStatus', realName: 'kycStatus' },
            { name: 'accountBlocked', realName: 'accountBlocked' },
            { name: 'isDeleted', realName: 'isDeleted' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = SwapXRESTB2BModelsUsersUpdateUserModel;
