/**
 * SWAPXRESTB2BAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of SwapXRESTB2BModelsBanksAddDepositViewModel
 */
class SwapXRESTB2BModelsBanksAddDepositViewModel extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.currencyId = this.constructor.getValue(obj.currencyId);
        this.depositAmount = this.constructor.getValue(obj.depositAmount);
        this.referenceNumber = this.constructor.getValue(obj.referenceNumber);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'currencyId', realName: 'currencyId' },
            { name: 'depositAmount', realName: 'depositAmount' },
            { name: 'referenceNumber', realName: 'referenceNumber' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = SwapXRESTB2BModelsBanksAddDepositViewModel;
