/**
 * SWAPXRESTB2BAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of SwapXCoreServicesV2ModelsApiRequestUsersWalletLoadInputModel
 */
class SwapXCoreServicesV2ModelsApiRequestUsersWalletLoadInputModel extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.currencyId = this.constructor.getValue(obj.currencyId);
        this.loadAmount = this.constructor.getValue(obj.loadAmount);
        this.addMemo = this.constructor.getValue(obj.addMemo);
        this.selectedUsers = this.constructor.getValue(obj.selectedUsers);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'currencyId', realName: 'currencyId' },
            { name: 'loadAmount', realName: 'loadAmount' },
            { name: 'addMemo', realName: 'addMemo' },
            { name: 'selectedUsers', realName: 'selectedUsers', array: true },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = SwapXCoreServicesV2ModelsApiRequestUsersWalletLoadInputModel;
