/**
 * SWAPXRESTB2BAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of SwapXRESTB2BModelsWalletsUserWalletModel
 */
class SwapXRESTB2BModelsWalletsUserWalletModel extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.userId = this.constructor.getValue(obj.userId);
        this.currencyId = this.constructor.getValue(obj.currencyId);
        this.amountAvailable = this.constructor.getValue(obj.amountAvailable);
        this.transactionNotSettledAmount =
          this.constructor.getValue(obj.transactionNotSettledAmount);
        this.lastTransactionDate = this.constructor.getValue(obj.lastTransactionDate);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'userId', realName: 'userId' },
            { name: 'currencyId', realName: 'currencyId' },
            { name: 'amountAvailable', realName: 'amountAvailable' },
            { name: 'transactionNotSettledAmount', realName: 'transactionNotSettledAmount' },
            {
                name: 'lastTransactionDate',
                realName: 'lastTransactionDate',
                isDateTime: true,
                dateTimeValue: 'rfc3339',
            },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = SwapXRESTB2BModelsWalletsUserWalletModel;
