/**
 * SWAPXRESTB2BAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of SwapXCoreServicesV2ModelsCardsTotalCardBalances
 */
class SwapXCoreServicesV2ModelsCardsTotalCardBalances extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.currencyId = this.constructor.getValue(obj.currencyId);
        this.currencyName = this.constructor.getValue(obj.currencyName);
        this.totalBalances = this.constructor.getValue(obj.totalBalances);
        this.totalBalancesDisplay = this.constructor.getValue(obj.totalBalancesDisplay);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'currencyId', realName: 'currencyId' },
            { name: 'currencyName', realName: 'currencyName' },
            { name: 'totalBalances', realName: 'totalBalances' },
            { name: 'totalBalancesDisplay', realName: 'totalBalancesDisplay' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = SwapXCoreServicesV2ModelsCardsTotalCardBalances;
