/**
 * SWAPXRESTB2BAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of SwapXRESTB2BModelsCardsCardFullPANResponseModel
 */
class SwapXRESTB2BModelsCardsCardFullPANResponseModel extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.cardId = this.constructor.getValue(obj.cardId);
        this.userId = this.constructor.getValue(obj.userId);
        this.fullPAN = this.constructor.getValue(obj.fullPAN);
        this.expiryMonth = this.constructor.getValue(obj.expiryMonth);
        this.expiryYear = this.constructor.getValue(obj.expiryYear);
        this.cvv = this.constructor.getValue(obj.cvv);
        this.nameOnCard = this.constructor.getValue(obj.nameOnCard);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'cardId', realName: 'cardId' },
            { name: 'userId', realName: 'userId' },
            { name: 'fullPAN', realName: 'fullPAN' },
            { name: 'expiryMonth', realName: 'expiryMonth' },
            { name: 'expiryYear', realName: 'expiryYear' },
            { name: 'cvv', realName: 'cvv' },
            { name: 'nameOnCard', realName: 'nameOnCard' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = SwapXRESTB2BModelsCardsCardFullPANResponseModel;
