/**
 * SWAPXRESTB2BAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of SwapXCoreServicesV2ModelsBasePagedList1SwapXRESTB2BModelsUsersDisplayUserModelSWAPXRESTB2BVersion2003CultureNeutralPublicKeyTokenNull
 */
class SwapXCoreServicesV2ModelsBasePagedList1SwapXRESTB2BModelsUsersDisplayUserModelSWAPXRESTB2BVersion2003CultureNeutralPublicKeyTokenNull
  extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.items = this.constructor.getValue(obj.items);
        this.count = this.constructor.getValue(obj.count);
        this.pageSize = this.constructor.getValue(obj.pageSize);
        this.currencySymbol = this.constructor.getValue(obj.currencySymbol);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            {
                name: 'items',
                realName: 'items',
                array: true,
                type: 'SwapXRESTB2BModelsUsersDisplayUserModel',
            },
            { name: 'count', realName: 'count' },
            { name: 'pageSize', realName: 'pageSize' },
            { name: 'currencySymbol', realName: 'currencySymbol' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = SwapXCoreServicesV2ModelsBasePagedList1SwapXRESTB2BModelsUsersDisplayUserModelSWAPXRESTB2BVersion2003CultureNeutralPublicKeyTokenNull;
