/**
 * SWAPXRESTB2BAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of SwapXRESTB2BModelsInsuranceRestCollisionInsuranceProperties
 */
class SwapXRESTB2BModelsInsuranceRestCollisionInsuranceProperties extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.providerName = this.constructor.getValue(obj.providerName);
        this.category = this.constructor.getValue(obj.category);
        this.location = this.constructor.getValue(obj.location);
        this.pickUpDate = this.constructor.getValue(obj.pickUpDate);
        this.dropOffDate = this.constructor.getValue(obj.dropOffDate);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'providerName', realName: 'providerName' },
            { name: 'category', realName: 'category' },
            { name: 'location', realName: 'location' },
            {
                name: 'pickUpDate',
                realName: 'pickUpDate',
                isDateTime: true,
                dateTimeValue: 'rfc3339',
            },
            {
                name: 'dropOffDate',
                realName: 'dropOffDate',
                isDateTime: true,
                dateTimeValue: 'rfc3339',
            },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = SwapXRESTB2BModelsInsuranceRestCollisionInsuranceProperties;
