/**
 * SWAPXRESTB2BAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of SwapXRESTB2BModelsAccountsOrganisationAccountDetailsModel
 */
class SwapXRESTB2BModelsAccountsOrganisationAccountDetailsModel extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.name = this.constructor.getValue(obj.name);
        this.totalCardBalance = this.constructor.getValue(obj.totalCardBalance);
        this.organisationWalletBalance = this.constructor.getValue(obj.organisationWalletBalance);
        this.cardIssued = this.constructor.getValue(obj.cardIssued);
        this.cardActive = this.constructor.getValue(obj.cardActive);
        this.cardBlocked = this.constructor.getValue(obj.cardBlocked);
        this.users = this.constructor.getValue(obj.users);
        this.pendingUsers = this.constructor.getValue(obj.pendingUsers);
        this.groups = this.constructor.getValue(obj.groups);
        this.companyReferenceNumber = this.constructor.getValue(obj.companyReferenceNumber);
        this.accountManager = this.constructor.getValue(obj.accountManager);
        this.accountManagerPhoneNumber = this.constructor.getValue(obj.accountManagerPhoneNumber);
        this.accountManagerEmail = this.constructor.getValue(obj.accountManagerEmail);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'name', realName: 'name' },
            {
                name: 'totalCardBalance',
                realName: 'totalCardBalance',
                array: true,
                type: 'SwapXCoreServicesV2ModelsCardsTotalCardBalances',
            },
            {
                name: 'organisationWalletBalance',
                realName: 'organisationWalletBalance',
                array: true,
                type: 'SwapXRESTB2BModelsWalletsUserWalletModel',
            },
            { name: 'cardIssued', realName: 'cardIssued' },
            { name: 'cardActive', realName: 'cardActive' },
            { name: 'cardBlocked', realName: 'cardBlocked' },
            { name: 'users', realName: 'users' },
            { name: 'pendingUsers', realName: 'pendingUsers' },
            { name: 'groups', realName: 'groups' },
            { name: 'companyReferenceNumber', realName: 'companyReferenceNumber' },
            { name: 'accountManager', realName: 'accountManager' },
            { name: 'accountManagerPhoneNumber', realName: 'accountManagerPhoneNumber' },
            { name: 'accountManagerEmail', realName: 'accountManagerEmail' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = SwapXRESTB2BModelsAccountsOrganisationAccountDetailsModel;
