/**
 * SWAPXRESTB2BAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of SwapXRESTB2BModelsInsuranceRestMedicalInsuranceProperties
 */
class SwapXRESTB2BModelsInsuranceRestMedicalInsuranceProperties extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.dateOfIncident = this.constructor.getValue(obj.dateOfIncident);
        this.description = this.constructor.getValue(obj.description);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            {
                name: 'dateOfIncident',
                realName: 'dateOfIncident',
                isDateTime: true,
                dateTimeValue: 'rfc3339',
            },
            { name: 'description', realName: 'description' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = SwapXRESTB2BModelsInsuranceRestMedicalInsuranceProperties;
