/**
 * SWAPXRESTB2BAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of SystemWebHttpValueProvidersValueProviderResult
 */
class SystemWebHttpValueProvidersValueProviderResult extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.attemptedValue = this.constructor.getValue(obj.attemptedValue);
        this.culture = this.constructor.getValue(obj.culture);
        this.rawValue = this.constructor.getValue(obj.rawValue);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'attemptedValue', realName: 'attemptedValue' },
            { name: 'culture', realName: 'culture' },
            { name: 'rawValue', realName: 'rawValue' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = SystemWebHttpValueProvidersValueProviderResult;
