/**
 * SWAPXRESTB2BAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';


const Configuration = {
    // The base Uri for API calls
    BASEURI: 'http://qa3.swapx.co.uk:89',

};

module.exports = Configuration;
