/**
 * SWAPXRESTB2BAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const SwapXRESTB2BModelsBanksBankAccountModel =
  require('../lib/Models/SwapXRESTB2BModelsBanksBankAccountModel');
const SwapXRESTB2BModelsBanksBankingPaymentModel =
  require('../lib/Models/SwapXRESTB2BModelsBanksBankingPaymentModel');
const SystemWebHttpModelBindingModelState =
  require('../lib/Models/SystemWebHttpModelBindingModelState');
const SystemWebHttpValueProvidersValueProviderResult =
  require('../lib/Models/SystemWebHttpValueProvidersValueProviderResult');
const SystemWebHttpModelBindingModelError =
  require('../lib/Models/SystemWebHttpModelBindingModelError');
const SwapXCoreServicesV2ModelsCardsCardModel =
  require('../lib/Models/SwapXCoreServicesV2ModelsCardsCardModel');
const SwapXRESTB2BModelsCardsOrderCardModel =
  require('../lib/Models/SwapXRESTB2BModelsCardsOrderCardModel');
const SwapXRESTB2BModelsUsersCardUserModel =
  require('../lib/Models/SwapXRESTB2BModelsUsersCardUserModel');
const SwapXRESTB2BModelsCardsBlockMccCardRequestModel =
  require('../lib/Models/SwapXRESTB2BModelsCardsBlockMccCardRequestModel');
const SwapXRESTB2BModelsCardsBlockMccCardDetailRequestModel =
  require('../lib/Models/SwapXRESTB2BModelsCardsBlockMccCardDetailRequestModel');
const SwapXRESTB2BModelsCardsCardFullPANRequestModel =
  require('../lib/Models/SwapXRESTB2BModelsCardsCardFullPANRequestModel');
const SwapXRESTB2BModelsCardsCardFullPANResponseModel =
  require('../lib/Models/SwapXRESTB2BModelsCardsCardFullPANResponseModel');
const SwapXRESTB2BModelsCurrenciesCurrencyInfoModel =
  require('../lib/Models/SwapXRESTB2BModelsCurrenciesCurrencyInfoModel');
const SwapXRESTB2BModelsCurrenciesCurrencyRateViewModel =
  require('../lib/Models/SwapXRESTB2BModelsCurrenciesCurrencyRateViewModel');
const SwapXCoreServicesV2ModelsFXTradeQuoteResponse =
  require('../lib/Models/SwapXCoreServicesV2ModelsFXTradeQuoteResponse');
const SwapXRESTB2BModelsHealthCheckHealthCheckInfoModel =
  require('../lib/Models/SwapXRESTB2BModelsHealthCheckHealthCheckInfoModel');
const SwapXRESTB2BModelsUserRestAddPolicyHolderModel =
  require('../lib/Models/SwapXRESTB2BModelsUserRestAddPolicyHolderModel');
const SwapXRESTB2BModelsUserRestInsurancePolicy =
  require('../lib/Models/SwapXRESTB2BModelsUserRestInsurancePolicy');
const SwapXRESTB2BModelsInsuranceRestTravelInsuranceProperties =
  require('../lib/Models/SwapXRESTB2BModelsInsuranceRestTravelInsuranceProperties');
const SwapXRESTB2BModelsInsuranceRestMedicalInsuranceProperties =
  require('../lib/Models/SwapXRESTB2BModelsInsuranceRestMedicalInsuranceProperties');
const SwapXRESTB2BModelsInsuranceRestGadgetInsuranceProperties =
  require('../lib/Models/SwapXRESTB2BModelsInsuranceRestGadgetInsuranceProperties');
const SwapXRESTB2BModelsInsuranceRestCollisionInsuranceProperties =
  require('../lib/Models/SwapXRESTB2BModelsInsuranceRestCollisionInsuranceProperties');
const SwapXCoreServicesV2ModelsRockPassengerInformation =
  require('../lib/Models/SwapXCoreServicesV2ModelsRockPassengerInformation');
const SwapXRESTB2BModelsInsuranceRestUpdatePolicyHolderModel =
  require('../lib/Models/SwapXRESTB2BModelsInsuranceRestUpdatePolicyHolderModel');
const SwapXCoreServicesV2ModelsBasePagedList1SwapXRESTB2BModelsUserRestDisplayUserRestModelSWAPXRESTB2BVersion2003CultureNeutralPublicKeyTokenNull =
  require('../lib/Models/SwapXCoreServicesV2ModelsBasePagedList1SwapXRESTB2BModelsUserRestDisplayUserRestModelSWAPXRESTB2BVersion2003CultureNeutralPublicKeyTokenNull');
const SwapXRESTB2BModelsUserRestDisplayUserRestModel =
  require('../lib/Models/SwapXRESTB2BModelsUserRestDisplayUserRestModel');
const SwapXRESTB2BModelsUserRestUpdatePolicy =
  require('../lib/Models/SwapXRESTB2BModelsUserRestUpdatePolicy');
const SwapXRESTB2BModelsUserRestAddPolicy =
  require('../lib/Models/SwapXRESTB2BModelsUserRestAddPolicy');
const SwapXRESTB2BModelsAccountsOrganisationAccountDetailsModel =
  require('../lib/Models/SwapXRESTB2BModelsAccountsOrganisationAccountDetailsModel');
const SwapXCoreServicesV2ModelsCardsTotalCardBalances =
  require('../lib/Models/SwapXCoreServicesV2ModelsCardsTotalCardBalances');
const SwapXRESTB2BModelsWalletsUserWalletModel =
  require('../lib/Models/SwapXRESTB2BModelsWalletsUserWalletModel');
const SwapXCoreServicesV2ModelsUserWalletWalletAmount =
  require('../lib/Models/SwapXCoreServicesV2ModelsUserWalletWalletAmount');
const SwapXRESTB2BModelsBanksAddDepositViewModel =
  require('../lib/Models/SwapXRESTB2BModelsBanksAddDepositViewModel');
const SwapXRESTB2BModelsCountriesDisplayCountryModel =
  require('../lib/Models/SwapXRESTB2BModelsCountriesDisplayCountryModel');
const SwapXRESTB2BModelsTransactionsTransactionPushInfo =
  require('../lib/Models/SwapXRESTB2BModelsTransactionsTransactionPushInfo');
const SwapXRESTB2BModelsTransactionsLoadPushInfo =
  require('../lib/Models/SwapXRESTB2BModelsTransactionsLoadPushInfo');
const SwapXRESTB2BModelsTransactionsUserTransactionModel =
  require('../lib/Models/SwapXRESTB2BModelsTransactionsUserTransactionModel');
const SwapXRESTB2BModelsUsersAddUserModel =
  require('../lib/Models/SwapXRESTB2BModelsUsersAddUserModel');
const SwapXRESTB2BModelsUsersDisplayUserModel =
  require('../lib/Models/SwapXRESTB2BModelsUsersDisplayUserModel');
const SwapXRESTB2BModelsUsersUpdateUserModel =
  require('../lib/Models/SwapXRESTB2BModelsUsersUpdateUserModel');
const SwapXCoreServicesV2ModelsBasePagedList1SwapXRESTB2BModelsUsersDisplayUserModelSWAPXRESTB2BVersion2003CultureNeutralPublicKeyTokenNull =
  require('../lib/Models/SwapXCoreServicesV2ModelsBasePagedList1SwapXRESTB2BModelsUsersDisplayUserModelSWAPXRESTB2BVersion2003CultureNeutralPublicKeyTokenNull');
const SwapXRESTB2BModelsUsersBasicUserInfoModel =
  require('../lib/Models/SwapXRESTB2BModelsUsersBasicUserInfoModel');
const SwapXRESTB2BModelsUsersUpdateUserAccountBlockModel =
  require('../lib/Models/SwapXRESTB2BModelsUsersUpdateUserAccountBlockModel');
const SwapXRESTB2BModelsUsersUpdateUser3DSInfoModel =
  require('../lib/Models/SwapXRESTB2BModelsUsersUpdateUser3DSInfoModel');
const SwapXCoreServicesV2ModelsApiRequestUsersWalletLoadInputModel =
  require('../lib/Models/SwapXCoreServicesV2ModelsApiRequestUsersWalletLoadInputModel');
const SwapXCoreModelsWalletUsersWalletLoadInputModel =
  require('../lib/Models/SwapXCoreModelsWalletUsersWalletLoadInputModel');
const SwapXCoreServicesV2ModelsUserWalletWalletAmountErrorException =
  require('../lib/Exceptions/SwapXCoreServicesV2ModelsUserWalletWalletAmountErrorException');
const SystemWebHttpModelBindingModelStateErrorException =
  require('../lib/Exceptions/SystemWebHttpModelBindingModelStateErrorException');

const classMap = {
    SwapXRESTB2BModelsBanksBankAccountModel,
    SwapXRESTB2BModelsBanksBankingPaymentModel,
    SystemWebHttpModelBindingModelState,
    SystemWebHttpValueProvidersValueProviderResult,
    SystemWebHttpModelBindingModelError,
    SwapXCoreServicesV2ModelsCardsCardModel,
    SwapXRESTB2BModelsCardsOrderCardModel,
    SwapXRESTB2BModelsUsersCardUserModel,
    SwapXRESTB2BModelsCardsBlockMccCardRequestModel,
    SwapXRESTB2BModelsCardsBlockMccCardDetailRequestModel,
    SwapXRESTB2BModelsCardsCardFullPANRequestModel,
    SwapXRESTB2BModelsCardsCardFullPANResponseModel,
    SwapXRESTB2BModelsCurrenciesCurrencyInfoModel,
    SwapXRESTB2BModelsCurrenciesCurrencyRateViewModel,
    SwapXCoreServicesV2ModelsFXTradeQuoteResponse,
    SwapXRESTB2BModelsHealthCheckHealthCheckInfoModel,
    SwapXRESTB2BModelsUserRestAddPolicyHolderModel,
    SwapXRESTB2BModelsUserRestInsurancePolicy,
    SwapXRESTB2BModelsInsuranceRestTravelInsuranceProperties,
    SwapXRESTB2BModelsInsuranceRestMedicalInsuranceProperties,
    SwapXRESTB2BModelsInsuranceRestGadgetInsuranceProperties,
    SwapXRESTB2BModelsInsuranceRestCollisionInsuranceProperties,
    SwapXCoreServicesV2ModelsRockPassengerInformation,
    SwapXRESTB2BModelsInsuranceRestUpdatePolicyHolderModel,
    SwapXCoreServicesV2ModelsBasePagedList1SwapXRESTB2BModelsUserRestDisplayUserRestModelSWAPXRESTB2BVersion2003CultureNeutralPublicKeyTokenNull,
    SwapXRESTB2BModelsUserRestDisplayUserRestModel,
    SwapXRESTB2BModelsUserRestUpdatePolicy,
    SwapXRESTB2BModelsUserRestAddPolicy,
    SwapXRESTB2BModelsAccountsOrganisationAccountDetailsModel,
    SwapXCoreServicesV2ModelsCardsTotalCardBalances,
    SwapXRESTB2BModelsWalletsUserWalletModel,
    SwapXCoreServicesV2ModelsUserWalletWalletAmount,
    SwapXRESTB2BModelsBanksAddDepositViewModel,
    SwapXRESTB2BModelsCountriesDisplayCountryModel,
    SwapXRESTB2BModelsTransactionsTransactionPushInfo,
    SwapXRESTB2BModelsTransactionsLoadPushInfo,
    SwapXRESTB2BModelsTransactionsUserTransactionModel,
    SwapXRESTB2BModelsUsersAddUserModel,
    SwapXRESTB2BModelsUsersDisplayUserModel,
    SwapXRESTB2BModelsUsersUpdateUserModel,
    SwapXCoreServicesV2ModelsBasePagedList1SwapXRESTB2BModelsUsersDisplayUserModelSWAPXRESTB2BVersion2003CultureNeutralPublicKeyTokenNull,
    SwapXRESTB2BModelsUsersBasicUserInfoModel,
    SwapXRESTB2BModelsUsersUpdateUserAccountBlockModel,
    SwapXRESTB2BModelsUsersUpdateUser3DSInfoModel,
    SwapXCoreServicesV2ModelsApiRequestUsersWalletLoadInputModel,
    SwapXCoreModelsWalletUsersWalletLoadInputModel,
    SwapXCoreServicesV2ModelsUserWalletWalletAmountErrorException,
    SystemWebHttpModelBindingModelStateErrorException,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
